# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trip_distance',
            new_name='distance',
        ),
    ]
